# Pandas accessing data
df.iloc[row, column]
df.loc[row, column]

In [1]:
# Import libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data clean up
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Generating train split: 100%|██████████| 785741/785741 [00:04<00:00, 157898.60 examples/s]

In [11]:
df

             job_title_short  ...                                    job_type_skills
0       Senior Data Engineer  ...                                                NaN
1               Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2              Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3              Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4              Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
...                      ...  ...                                                ...
785736     Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737          Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738      Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739         Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740     Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[785741 rows x 17 columns]

In [ ]:
df.iloc[0:5, 5]
# Can be complicated if i need various coloumn displayed as it relies on index

0    False
1    False
2    False
3    False
4    False
Name: job_work_from_home, dtype: bool

In [ ]:
df.loc[:, 'salary_rate' : 'salary_hour_avg'].dropna(subset='salary_rate')
# .loc allows us to find the data by its label

                                          job_skills                                    job_type_skills
0                                                NaN                                                NaN
1  ['r', 'python', 'sql', 'nosql', 'power bi', 't...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2  ['python', 'sql', 'c#', 'azure', 'airflow', 'd...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3  ['python', 'c++', 'java', 'matlab', 'aws', 'te...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4  ['bash', 'python', 'oracle', 'aws', 'ansible',...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
5                           ['python', 'sql', 'gcp']  {'cloud': ['gcp'], 'programming': ['python', '...
6  ['sql', 'python', 'java', 'sql server', 'gcp',...  {'cloud': ['gcp', 'bigquery'], 'databases': ['...
7  ['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...  {'cloud': ['gcp', 'azure', 'aws', 'bigquery', ...
8                ['excel', 'powerpoint', 'power bi']  {'analyst_tools': ['excel', 'powerpoint', 'pow...
9  ['sql', 'python', 'r', 'mongodb', 'mongodb', '...  {'analyst_tools': ['excel'], 'cloud': ['azure'...

In [ ]:
df.loc[0:9,['job_skills', 'job_type_skills']]
# Get the first 10 rows of job_skills and job_type_skills

                                          job_skills                                    job_type_skills
0                                                NaN                                                NaN
1  ['r', 'python', 'sql', 'nosql', 'power bi', 't...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2  ['python', 'sql', 'c#', 'azure', 'airflow', 'd...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3  ['python', 'c++', 'java', 'matlab', 'aws', 'te...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4  ['bash', 'python', 'oracle', 'aws', 'ansible',...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
5                           ['python', 'sql', 'gcp']  {'cloud': ['gcp'], 'programming': ['python', '...
6  ['sql', 'python', 'java', 'sql server', 'gcp',...  {'cloud': ['gcp', 'bigquery'], 'databases': ['...
7  ['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...  {'cloud': ['gcp', 'azure', 'aws', 'bigquery', ...
8                ['excel', 'powerpoint', 'power bi']  {'analyst_tools': ['excel', 'powerpoint', 'pow...
9  ['sql', 'python', 'r', 'mongodb', 'mongodb', '...  {'analyst_tools': ['excel'], 'cloud': ['azure'...