# Applying funtions
apply()

In [8]:
# Import libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data clean up
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Let say we want to calculate the expected salary with inflation

In [9]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary(salary):
    return salary * 1.03

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)
# apply simply run this function separately on each item in that column 
# df_salary['salary_year_inflated'] = projected_salary(df_salary['salary_year_avg'])
# df_salary['salary_year_inflated'] = df_salary['salary_year_avg'] * 1.03
# df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)



df_salary[['salary_year_inflated', 'salary_year_avg']]

        salary_year_inflated  salary_year_avg
28                 112785.00         109500.0
77                 144200.00         140000.0
92                 123600.00         120000.0
100                235068.66         228222.0
109                 91670.00          89000.0
...                      ...              ...
785624             143392.48         139216.0
785641             154500.00         150000.0
785648             228531.25         221875.0
785682             162225.00         157500.0
785692             162225.00         157500.0

[22003 rows x 2 columns]

Convert skills set back to a list (rather than str)

In [10]:
import ast

In [11]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)


df['job_skills'] = df['job_skills'].apply(clean_list)

In [ ]:
#same as above, with lambda
df['job_skills'] = df['job_skills'].apply(
    lambda x: ast.literal_eval(x) if pd.notna(x) else x)

## For Rows 
* senior role 5%
* other role 3%

In [15]:
def projected_salary(row):
    if 'Senior' in row['job_title_short']:
        return row['salary_year_avg'] * 1.05
    else:
        return row['salary_year_avg'] * 1.03

df['salary_adjusted'] = df.apply(projected_salary, axis=1)

In [ ]:
#Lambda version again, note that x can be named anythiing
df['salary_adjusted'] = df.apply(
    lambda x: x['salary_year_avg'] * 1.05
    if 'Senior' in x['job_title_short']
    else x['salary_year_avg'] * 1.03,
    axis=1
)

In [25]:
df[['salary_adjusted', 'salary_year_avg']].sample(10)

        salary_adjusted  salary_year_avg
529749              NaN              NaN
235029              NaN              NaN
593607              NaN              NaN
585353              NaN              NaN
410030         133900.0         130000.0
274650          87550.0          85000.0
307549              NaN              NaN
292681         147000.0         140000.0
73322               NaN              NaN
393627              NaN              NaN