# Data management
df.sample()
df.copy()

In [1]:
# Import libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data clean up
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

/opt/anaconda3/envs/python_beginner_course/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
510186,Data Analyst,Junior Data Loss Prevention Analyst,"Kraków, Poland",via LinkedIn,Full-time,False,Poland,2023-04-25 11:24:47,False,False,Poland,NaN,NaN,NaN,dunnhumby,NaN,NaN
635614,Business Analyst,Senior Business Analyst (f/m/d),"Berlin, Germany",via StepStone,Full-time,False,Germany,2023-03-07 12:40:50,False,False,Germany,NaN,NaN,NaN,Ladenzeile GmbH,"['sql', 'python']","{'programming': ['sql', 'python']}"
117176,Data Analyst,Data Analyst,"Cebu City, Cebu, Philippines",via Indeed,Full-time,False,Philippines,2023-10-25 08:14:54,True,False,Philippines,NaN,NaN,NaN,Rural Net Inc.,"['sql', 'postgresql', 'excel', 'power bi', 'sa...","{'analyst_tools': ['excel', 'power bi', 'sap',..."
244923,Senior Data Analyst,Sr Fraud Insights and Intelligence Analyst,Canada,via BeBee Canada,Full-time,False,Canada,2023-07-14 07:11:23,False,False,Canada,NaN,NaN,NaN,Definity Financial Corporation,"['python', 'r', 'java', 'go', 'tableau', 'powe...","{'analyst_tools': ['tableau', 'power bi', 'exc..."
319212,Data Analyst,Data Analyst:in im Vertriebsinnendienst (m/w/d),"Vienna, Austria",via LinkedIn,Full-time,False,Austria,2023-05-04 17:30:58,True,False,Austria,NaN,NaN,NaN,LP Experts Personalmanagement GmbH,"['excel', 'power bi', 'dax', 'sap']","{'analyst_tools': ['excel', 'power bi', 'dax',..."
543825,Business Analyst,Analyst,"Hyderabad, Telangana, India",via LinkedIn,Full-time,False,India,2023-04-05 19:12:31,False,False,India,NaN,NaN,NaN,Thomson Reuters,NaN,NaN
764416,Data Engineer,Data Engineer H/F (IT) / Freelance,"Montreuil, France",via LinkedIn,Full-time,False,France,2023-09-19 20:24:52,True,False,France,NaN,NaN,NaN,exteam,"['python', 'sql', 'nosql', 'mongodb', 'mongodb...","{'async': ['jira'], 'cloud': ['oracle', 'aws',..."
717707,Software Engineer,Junior Project Manager,"Riga, Latvia",via Trabajo.org,Full-time,False,Latvia,2023-01-22 03:11:41,False,False,Latvia,NaN,NaN,NaN,Alstom,NaN,NaN
108736,Senior Data Scientist,Data Scientist / Senior Data Scientist,Singapore,via Melga,Contractor,False,Singapore,2023-02-22 00:32:31,False,False,Singapore,NaN,NaN,NaN,AZENDIAN SOLUTIONS PTE. LTD.,"['sas', 'sas', 'r', 'python', 'sql', 'spss', '...","{'analyst_tools': ['sas', 'spss'], 'other': ['..."
398239,Data Analyst,Data Analyst/Report Writer,"Austin, TX",via Dice,Contractor,False,"Texas, United States",2023-10-25 18:01:20,False,False,United States,NaN,NaN,NaN,Neos Consulting,"['sql', 'sas', 'sas', 'sql server', 'oracle', ...","{'analyst_tools': ['sas', 'excel', 'ssis', 'ss..."

In [ ]:
df.sample(5, random_state = 42)
# Give same 5 random sample when we use 42 as numbee

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}

In [9]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [ ]:
df_altered = df_original
# The problem here is: if we update the df_altered (e.g. fillna), the df.original will also be updated
# Their ID is the same

In [10]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [11]:
df_altered = df_original.copy()

In [12]:
id(df_altered) == id(df_original)

False