In [36]:
# Import libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data clean up
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [37]:
df_usa = df[df['job_country']=='United States'].copy()

In [38]:
df_usa['job_posted_month'] = df_usa['job_posted_date'].dt.strftime('%B')

In [39]:
usa_pivot = df_usa.pivot_table(index= 'job_posted_month', columns='job_title_short', aggfunc= 'size')
usa_pivot

job_title_short,Business Analyst,Cloud Engineer,Data Analyst,Data Engineer,Data Scientist,Machine Learning Engineer,Senior Data Analyst,Senior Data Engineer,Senior Data Scientist,Software Engineer
job_posted_month,,,,,,,,,,
April,565,40,6049,2801,4867,51,1025,781,991,112
August,903,39,6634,3269,6318,68,1186,903,1515,194
December,648,40,3979,2641,3472,119,601,689,752,212
February,447,24,6124,3060,4956,56,1258,878,1127,90
January,527,36,8494,2655,6915,60,1544,773,1552,114
July,581,39,5201,2570,4876,65,883,747,1095,153
June,446,32,5683,2893,4645,48,1009,812,1033,93
March,438,19,6218,3183,4779,59,1114,829,1150,115
May,279,20,4993,2976,4377,49,839,746,914,90
November,719,36,4531,2793,4175,132,656,684,816,194
October,932,48,5271,3015,4882,101,871,672,987,219
September,897,50,4639,3224,4568,113,805,775,1014,228

In [40]:
usa_pivot.reset_index(inplace=True)

In [41]:
usa_pivot['month_no'] = pd.to_datetime(usa_pivot['job_posted_month'], format='%B').dt.month
usa_pivot

job_title_short,job_posted_month,Business Analyst,Cloud Engineer,Data Analyst,Data Engineer,Data Scientist,Machine Learning Engineer,Senior Data Analyst,Senior Data Engineer,Senior Data Scientist,Software Engineer,month_no
0,April,565,40,6049,2801,4867,51,1025,781,991,112,4
1,August,903,39,6634,3269,6318,68,1186,903,1515,194,8
2,December,648,40,3979,2641,3472,119,601,689,752,212,12
3,February,447,24,6124,3060,4956,56,1258,878,1127,90,2
4,January,527,36,8494,2655,6915,60,1544,773,1552,114,1
5,July,581,39,5201,2570,4876,65,883,747,1095,153,7
6,June,446,32,5683,2893,4645,48,1009,812,1033,93,6
7,March,438,19,6218,3183,4779,59,1114,829,1150,115,3
8,May,279,20,4993,2976,4377,49,839,746,914,90,5
9,November,719,36,4531,2793,4175,132,656,684,816,194,11
10,October,932,48,5271,3015,4882,101,871,672,987,219,10
11,September,897,50,4639,3224,4568,113,805,775,1014,228,9

In [42]:
usa_pivot.sort_values('month_no', inplace = True)
usa_pivot.set_index('job_posted_month', inplace = True)
usa_pivot.drop(columns='month_no', inplace = True)

In [43]:
usa_pivot

job_title_short,Business Analyst,Cloud Engineer,Data Analyst,Data Engineer,Data Scientist,Machine Learning Engineer,Senior Data Analyst,Senior Data Engineer,Senior Data Scientist,Software Engineer
job_posted_month,,,,,,,,,,
January,527,36,8494,2655,6915,60,1544,773,1552,114
February,447,24,6124,3060,4956,56,1258,878,1127,90
March,438,19,6218,3183,4779,59,1114,829,1150,115
April,565,40,6049,2801,4867,51,1025,781,991,112
May,279,20,4993,2976,4377,49,839,746,914,90
June,446,32,5683,2893,4645,48,1009,812,1033,93
July,581,39,5201,2570,4876,65,883,747,1095,153
August,903,39,6634,3269,6318,68,1186,903,1515,194
September,897,50,4639,3224,4568,113,805,775,1014,228
October,932,48,5271,3015,4882,101,871,672,987,219
November,719,36,4531,2793,4175,132,656,684,816,194
December,648,40,3979,2641,3472,119,601,689,752,212

In [49]:
top_3 = df_usa['job_title_short'].value_counts().head(3)
top_3 = top_3.index.to_list()
top_3

['Data Analyst', 'Data Scientist', 'Data Engineer']

In [51]:
usa_pivot[top_3]

job_title_short   Data Analyst  Data Scientist  Data Engineer
job_posted_month
January                   8494            6915           2655
February                  6124            4956           3060
March                     6218            4779           3183
April                     6049            4867           2801
May                       4993            4377           2976
June                      5683            4645           2893
July                      5201            4876           2570
August                    6634            6318           3269
September                 4639            4568           3224
October                   5271            4882           3015
November                  4531            4175           2793
December                  3979            3472           2641